### PR TITLE
Added list of programming languages to stopwords

### PR DESCRIPTION
**Pull request by rootAvish**
These are all the programming languages supported by Github. May
help to improve the quality of tags for PGM.
Source: https://github.com/csurfer/gitlang/blob/master/languages.txt

### CODE REVIEW

**Comment by fridex** [comment]
I'm really unsure about this. If we add such stopwords a lot of packages wouldn't be flagged with keywords.

Take [this package](http://mvnrepository.com/artifact/org.jetbrains.kotlin/kotlin-reflect) as an example. It's a Kotlin reflection library that is a package on maven. I think Kotlin keyword is really appropriate there. Also many other libraries that are some bindings or so (e.g. optimized Python libraries written in C, Java language specific libraries in maven ecosystem, ...).

**Comment by rootAvish** [comment]
I see, however if we can achieve an overall accuracy that's better than the previous iteration with this list in place I'm fine with "less than optimal" labelling for some packages, which is why I wanted to do a test run with these stop words. Do you have a VM we can maybe schedule the tagger on? I would have to leave my local machine on for a very long time to test all packages.

**Comment by tisnik** [comment]
[test]

**Comment by tisnik** [comment]
[test]

**Comment by rootAvish** [comment]
Stale, so closing.

**Pull request closed without merging**
