### PR TITLE
Add fallback for virtualenv binary due to CentOS

### PR DESCRIPTION
**Pull request by pkajaba**

### CODE REVIEW

**Comment by msrb** [comment]
[test]

**Comment by pkajaba** [comment]
It was successful for the second time but we are still missing approval from centos-ci user as collaborator (I guess)

https://ci.centos.org/job/devtools-fabric8-analytics-tagger-fabric8-analytics-pylint/2/console

**Comment by fridex** [comment]
> It was successful for the second time but we are still missing approval from centos-ci user as collaborator (I guess).

Re-requested, pending approval.

**Comment by tisnik** [comment]
LGTM, thanks a lot @pkajaba

**Pull request merged**
